name: innostrategy
favicon: null
layout_spectrum: 0.25294
typography_spectrum: 0.7563650840893388
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.2829932936001569
  lightness: 0.2780682994052768
  saturation: 0.08597896574065089
  rhythmicContrast: 0.9711225193459541
purpose: []
